Try new travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,57 +1,52 @@
-language: haskell
+# See https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System
+sudo: required
+
+# Choose a lightweight base image; we provide our own build tools.
+language: generic
+
+# Caching so the next build will be fast too.
+cache:
+  directories:
+  - "$HOME/.stack"
+
+# GHC depends on GMP. You can add other dependencies here as well.
+addons:
+  apt:
+    packages:
+    - libgmp-dev
+
+# The different configurations we want to test. You could also do things like
+# change flags or use --stack-yaml to point to a different file.
+# See list here -- https://www.stackage.org/snapshots
 env:
-  #- GHCVER=7.8.1
-  - GHCVER=7.10.1
-  # doctest doesnt build with ghc 8.* yet
-  #- GHCVER=head
-
-branches:
-    only:
-        -   master
-
-notifications:
-  webhooks:
-    urls:
-        -   https://webhooks.gitter.im/e/e80ceb37bab1d58c4128
-    on_success: always  # options: [always|never|change] default: always
-    on_failure: always  # options: [always|never|change] default: always
-    on_start: false     # default: false
+- $RESOLVER="lts-10.10"
+- $RESOLVER="lts-11.22"
 
 before_install:
-  # If $GHCVER is the one travis has, don't bother reinstalling it.
-  # We can also have faster builds by installing some libraries with
-  # `apt`. If it isn't, install the GHC we want from hvr's PPA along
-  # with cabal-1.18.
-  - |
-    if [ $GHCVER = `ghc --numeric-version` ]; then
-      # Try installing some of the build-deps with apt-get for speed.
-      travis/cabal-apt-install --enable-tests $MODE
-      export CABAL=cabal
-    else
-      # Install the GHC we want from hvr's PPA
-      travis_retry sudo add-apt-repository -y ppa:hvr/ghc
-      travis_retry sudo apt-get update
-      travis_retry sudo apt-get install cabal-install-1.22 ghc-$GHCVER happy
-      export CABAL=cabal-1.22
-      export PATH=/opt/ghc/$GHCVER/bin:$PATH
-      ghc --version
-    fi
-  # Uncomment whenever hackage is down.
-  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && $CABAL update
-  - $CABAL update
-
-  # Update happy when building with GHC head
-  - |
-    $CABAL install happy alex
-    export PATH=$HOME/.cabal/bin:$PATH
+# Download and unpack the stack executable -- https://docs.haskellstack.org/en/stable/travis_ci/?highlight=travis
+- mkdir -p ~/.local/bin
+- export PATH=$HOME/.local/bin:$PATH
+- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 
 install:
-  - $CABAL install Cabal-1.22.4.0
-  - $CABAL sandbox init
-  - $CABAL install --dependencies-only --enable-tests --shadow-installed-packages
-  - $CABAL configure -flib-Werror --enable-tests $MODE
+# Build dependencies
+- stack --resolver $RESOLVER --no-terminal --install-ghc test --only-dependencies
 
 script:
-  - $CABAL build
-  - $CABAL test --show-details=always
+# Build the package, its tests, and its docs and run the tests
+- stack --resolver $RESOLVER --no-terminal --install-ghc test --haddock --no-haddock-deps
+# List components explicitly; ignoring failure
+- stack --resolver $RESOLVER exec ghc-pkg list || true
 
+## Deploy (tagged commits) to Hackage; generated by travis CLI
+#before_deploy: "echo '=== BEGIN deployment ==='"
+#deploy:
+#  provider: hackage
+#  username: Orome
+#  password:
+#    secure: lJTICRAD8m+NePYSnyol1TU1zAyuv9YUmR1mfqE5qTrJnauERarmMEVJXglQUASyAT+JfLSoRqJfQWcixE1YTmcXrijIxZicX7G/t6FqPrJDiz+7lpCg4sXBa4ZAbahwvprkBB1eJUN+/9MUjEeX8a+N/lT/hTvnoAFiM2SW1tfS9YuYTeKYCBNMgh6Li8X4cwvI0nsyWyDj7Q+2n1rti6yBSSt2NdXpxVUGzmn4TiDjbX6B3VNZSlwhMb7h9nw11Yf6UkbjI5r4G8eUAJ5o+YOpVGK41+2IXITrO6YnR7Ma3EmMiOADuG1KkJEUrc9juWy6RmjFO+Zs2YIHiYPKoLZXR1w1pRuSlre3vLJwMKj3nFF2aAgawzjqGpmtJlJLn1D+uIrMnUo5lNb4VNHDNTnlmnQAESZmK/lhhqOp/2CebVp0e2p2bjnJUHKVb3ptXmzek9ppS6T9fBhu9/am/4N3Yi1EUurlxVl0xE1eL/3zQX7vVwPrrjk6kDHgVqrlRDZWvf4/MBgyRUitE12w1oRr04cgcivtv2ipov30EdQoUpMy3ABq8EMITAFXTeNPWtEL+3XUqp9SQfxxnycK1Zm/xAsNgIDQl27xY+XYgF585A+cAkhjXkOhS2h7vDw7z2CXDpXcw46IcyoXiPI+9doLX9rTJF8rzJLVksGbPrE=
+#  on:
+#    repo: orome/crypto-enigma-hs
+#    branch: hackage
+#    tags: true
+#after_deploy: "echo '=== END deployment ==='"
